language: generic
sudo: false
dist: trusty

addons:
  apt:
    sources:
      - deadsnakes
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - libsparsehash-dev
      - python3.6
      - python3-yaml
      - cmake
      - netcat

cache:
  directories:
    - e2e_data/scientist-collection/

env:
  - CC=gcc-7 CXX=g++-7

before_script:
  - $CXX --version
  - mkdir build
  - cd build
  - cmake ..

script:
  - make -j 3
  - make test
  - cd ..
  - e2e/e2e.sh

notifications:
  email:
    on_success: never
    on_failure: always
