language: generic
sudo: required


# We need a newer docker version since our multi-stage build
# relies on old stages not leaking into the current stage
# see https://github.com/moby/moby/issues/35641
addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

script:
  - docker build -t qlever .
  - docker run -it --rm --entrypoint e2e/e2e.sh qlever

notifications:
  email:
    on_success: never
    on_failure: always
