language: cpp

compiler:
  - gcc

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libsparsehash-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make && make test
