language: c++
sudo: false
dist: trusty


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - libsparsehash-dev
      - cmake

compiler:
  - gcc-5

before_script:
  - $CXX --version
  - mkdir build
  - cd build
  - cmake ..

script: 
  - make -j 3 
  - make test

notifications:
  email:
    on_success: never
    on_failure: always
